stages:
  split:
    cmd: python split.py --data_path /Users/pauldev/delo/projects/risk-ai-workshop/notebooks/data/default.csv
    deps:
    - ../../notebooks/data/default.csv
    - split.py
    params:
    - split.non_target_cols
    - split.seed
    - split.target_col
    - split.test_ratio
    - split.train_ratio
    outs:
    - ../../notebooks/data/split
