# This is a basic workflow to help you get started with Actions

name: CI-CD

# Controls when the workflow will run
on: push

env:
  PROJECT_ROOT: ${{ github.workspace }}

jobs:
  tests:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.6", "3.7", "3.8", "3.9"]

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade coverage[toml] virtualenv tox tox-gh-actions
          python -m pip install -r requirements.txt
          python -m pip install .
      - name: "Run tox targets for ${{ matrix.python-version }}, ${{ matrix.os }}"
        run: "python -m tox"
      - name: "Run package tests for ${{ matrix.python-version }}, ${{ matrix.os }}"
        run: "python -m pytest -vv -m 'not latex and not notebook'"
      - name: "Run notebook tests for ${{ matrix.python-version }}, ${{ matrix.os }}"
        run: |
          sudo apt-get install graphviz
          python -m pytest -vv -m notebook
      - name: "Run latex tests for ${{ matrix.python-version }}, ${{ matrix.os }}"
        run: |
          sudo apt-get install texlive-latex-extra
          python -m pytest -vv -m latex

  deliver:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies for latex slide delivery"
        run: |
          sudo apt-get install texlive-latex-extra
          python -VV
          python -m site
          python -m pip install .

      - name: "Create slides"
        run: |
          mkdir -p tex_out

          python risk_learning/tex.py --filepath ${{ github.workspace }}/slides/intro/ai-risk-and-discrete-geometry.tex --outdir ${{ github.workspace }}/tex_out
          python risk_learning/tex.py --filepath ${{ github.workspace }}/slides/discrete-geometry/discrete-geometry.tex --outdir ${{ github.workspace }}/tex_out
          python risk_learning/tex.py --filepath ${{ github.workspace }}/slides/correlation-causality/correlation-causality.tex --outdir ${{ github.workspace }}/tex_out
          python risk_learning/tex.py --filepath ${{ github.workspace }}/slides/risk-and-ai-in-practice/risk-ai-practice.tex --outdir ${{ github.workspace }}/tex_out

          cd tex_out
          ls -al
      - name: "Archive slide artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: risk-ai-slides
          path: ${{ github.workspace }}/tex_out/*.pdf