# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: push

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade coverage[toml] virtualenv tox tox-gh-actions
          python -m pip install -r requirements.txt
          python -m pip install .

      - name: "Run tox targets for ${{ matrix.python-version }}"
        run: "python -m tox"
      - name: "Run tests for ${{ matrix.python-version }}"
        run: "python -m pytest -vv"
